blog_app/urls.py
from django.urls import path
from .import views
app_name='blog_app'
urlpatterns=[
    path('',views.index,name='index'),
    path('createaccount',views.createaccount,name='createaccount'),
    path('createpost',views.createpost,name='createpost'),
    path('login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout'),
    path('myprofile',views.myprofile,name='myprofile'),
    path('editpost/<int:id>',views.editpost,name='editpost'),
    path('deletepost/<int:id>',views.deletepost,name='deletepost')
]

blog_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('blog_app.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class user_model(models.Model):
    models.OneToOneField(User,on_delete=models.CASCADE)
       
class post_model(models.Model):
    description=models.CharField(max_length=1000,blank=True)
    image=models.FileField(upload_to='images/',blank=True)
    date=models.DateTimeField(blank=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True)

    def __str__(self):
        return self.user.username

blog_app/forms.py
from django import forms
from .models import user_model,post_model
from django.contrib.auth.models import User

class user_form(forms.ModelForm):
    username=forms.CharField(help_text=None)
    password=forms.CharField(widget=forms.PasswordInput)
    confirm_password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username','email','password','confirm_password')

class post_form(forms.ModelForm):
    class Meta:
        model = post_model
        fields='__all__'



blog_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect,HttpResponse
from .forms import user_form,post_form
from .models import user_model,post_model,User
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
import datetime

# Create your views here.
def index(request):
    models=post_model.objects.all()
    umodel=User.objects.all()
    model=[]
    for i in models:
        model=[i]+model
    return render(request,'index.html',{'model':model,'umodel':umodel})

def createaccount(request):
    if request.method == 'POST':
        user_form1=user_form(request.POST)
        password=request.POST.get('password')
        confirm_password=request.POST.get('confirm_password')
        if password == confirm_password:
            if user_form1.is_valid():
                form=user_form1.save()
                form.set_password(form.password)
                form.save()
                username = request.POST.get('username')
                password = request.POST.get('password')
                user = authenticate(username=username,password=password)
                if user:
                    if user.is_active:
                        login(request,user)
                        # formB.key = request.user
                        # formB.formA=formA
                        # formB.save()
                        return HttpResponseRedirect(reverse('blog_app:index'))
        else:
            return HttpResponse("Confirm Password didn't Match")
    else:
        user_form1=user_form()
    return render(request,'createaccount.html',{'user_form':user_form1})

def createpost(request):
    if request.method == 'POST':
        form=post_form(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.date = datetime.datetime.now()
            instance.save()
        return redirect('blog_app:index')
    return render(request,'createpost.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            print(user)
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('blog_app:index'))
            else:
                return HttpResponse('User Not Active')
        else:
            return HttpResponse('Incorret Creds')

    return render(request,'login.html',)

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog_app:index'))

def myprofile(request):
    models=post_model.objects.all().filter(user=request.user)
    model=[]
    for i in models:
        model=[i]+model
    return render(request,'myprofile.html',{'model':model})

def editpost(request,id):
    ed=post_model.objects.get(id=id)
    details={
        'image':ed.image,
        'description':ed.description
    }
    if request.method == 'POST':
        form = post_form(request.POST)
        if form.is_valid():
            post_model.objects.filter(id=id).update(description=form.cleaned_data['description'])
            return redirect('blog_app:index')
    return render(request,'editpost.html',{'details':details,'ed':ed})

def deletepost(request,id):
    post=post_model.objects.get(id=id)
    post.delete()
    return redirect('blog_app:index')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>
<body >
    <nav class="navbar navbar-expand-lg bg-body-tertiary" >
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'blog_app:index' %}"><b><i>BLOGPOST</i></b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          {% if user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog_app:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog_app:myprofile' %}">My Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog_app:logout' %}">Logout</a>
              </li>
            </ul>   
          </div>
          {% endif %}
        </div>
      </nav>
</body>
</html>
{% block content %}

{% endblock %}

templates/createaccount.html
{% extends 'base.html' %}
{% block content %}
<br><br>
<h2 align="center">Create Account</h2>
<br>
<center>
    <form method="POST">
        {% csrf_token %}
        <table>
        {{user_form.as_table}}
        </table>
        <br><br>
        <input type="submit" value="Create Account" class="btn btn-dark">
        <a href="{% url 'blog_app:index' %}" class="btn btn-dark">Back</a>
    </form>
</center>
{% endblock %}

templates/createpost.html
{% extends 'base.html' %}
{% block content %}
<br>
<h2 align="center"><b>Create Post</b></h2>
<form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <div class="container" style="position: relative; left: 350px;">
        <div class="jumbotron" >
            <div class="card w-50 mb-3" style="border: 0px;">
                <div class="card-body">
                    <div class="w-75 mb-3">
                        <label for="formFile" class="form-label">Image</label>
                        <input class="form-control" multiple type="file" name="image" id="formFile">
                    </div>
                    <div class="w-75 mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Description</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" name="description" rows="3"></textarea>
                    </div>
                    <div class="w-75 mb-3">
                        <input type="submit" value="Post" class="btn btn-outline-success">
                    </div>
                </div>
            </div>  
        </div>
    </div>
</form>

{% endblock %}

templates/editpost.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-6"><br>
            <div class="card-header"><i class="fa-solid fa-address-card fa-lg"></i><h4><b>Edit Post</b></h4></div>
                <form action="{% url 'blog_app:editpost' ed.id %}" enctype="application/x-www-form-urlencoded" method="POST">
                    {% csrf_token %}
                            <div class="card w-50 mb-3" style="border: 0px;">
                                <div class="card-body">
                                    {% if details.image %}
                                    <div class="w-75 mb-3">
                                        <img src="{{ details.image.url }}" alt="" width="75%">
                                    </div>
                                    {% endif %}
                                    <div class="w-75 mb-3">
                                        <textarea class="form-control" id="exampleFormControlTextarea1" name="description" rows="3">{{ details.description }}</textarea>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Save Changes</button>
                                    <a href="{% url 'blog_app:myprofile' %}" class="btn btn-secondary">Cancel</a>
                                </div>
                            </div>  
            
                    
                </form>
            </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% if user.is_authenticated %}
<br>
<h2 align="center" style=" font-family:'Times New Roman',serif ;color:chocolate;">Home</h2>
<hr>
<center><a href="{% url 'blog_app:createpost' %}" class="btn btn-outline-success">Create Post</a></center>
{% if model %}
<div class="container">
    <div class="jumbotron">
        <div class="row">
            {% for i in model %}
            <div class="col-md-12">
                <div class="card card-body w-50" style="border: 0;">
                    <ul style="list-style-type: none;">
                        <li><h4 style="font-size:25px;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color:darkred;">{{i.user.username}}</h4></li>
                            {% if i.user.username == user.username%} 
                            <div class="dropdown" style=" padding: 0px;margin: 0px;position: relative; left:200px; bottom: 37px;">
                                <img src="{% static 'images/dots.png' %}" alt="no img" data-bs-toggle="dropdown" width="20px">
                                <ul class="dropdown-menu">
                                  <li><a class="dropdown-item" href="{% url 'blog_app:editpost' i.id %}">Edit</a></li>
                                  <li><a class="dropdown-item" href="{% url 'blog_app:deletepost' i.id %}">Delete</a></li>
                                </ul>
                              </div>
                            {% endif %}
                        <li><p style="font-size:medium; font-family:Helvetica">{{i.description}}</p></li>
                        {% if i.image %}
                        <li><img src="{{ i.image.url }}" alt="no img" width="75%"></li>
                        {% endif %}
                        <li><p style="color: rgb(100, 100, 100); font-size:smaller;">{{i.date}}</p></li>
                    </ul>
                </div>
                <hr><hr>
            </div>  
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
<center><b><h4 style="font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">NO POSTS</h4></b></center>
{% endif %}
{% else %}
<br><br>
<center>
<div class="container">
    <a href="{% url 'blog_app:login' %}" class="btn btn-outline-dark">Login</a><br><br>
    <h5>or</h5><br>
    <a href="{% url 'blog_app:createaccount' %}" class="btn btn-outline-dark">Create Account</a>
</div>
</center>
{% endif %}


{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
<br><br>
<h2 align="center">Login</h2>
<br>
<center>
    <form method="POST">
        {% csrf_token %}
            <label for="">Username :</label>  <input type="text" name="username" id=""><br><br>
            <label for="">Password :</label>   <input type="password" name="password" id="">
            <br><br>
            <input type="submit" value="Login" class="btn btn-dark">
            <a href="{% url 'blog_app:index' %}" class="btn btn-dark">Back</a>
    </form>
</center>
{% endblock %}

templates/myprofile.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<br>
<h2 align="center" style="font-family:'Times New Roman',serif ;color:chocolate;">My Profile</h2>
<hr>
<center><a href="{% url 'blog_app:createpost' %}" class="btn btn-outline-success">Create Post</a></center>
{% if model %}
<div class="container">
    <div class="jumbotron">
        <div class="row">
            {% for i in model %}
            
            <div class="col-md-12">
                <div class="card card-body w-50" style="border: 0;">
                    <ul style="list-style-type: none;">
                        <li><h4 style="font-size:25px;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: darkred;" ><b>{{i.user.username}}</b></h4></li>
                        {% if i.user.username == user.username%} 
                            <div class="dropdown" style=" padding: 0px;margin: 0px;position: relative; left:200px; bottom: 37px;">
                                <img src="{% static 'images/dots.png' %}" alt="no img" data-bs-toggle="dropdown" width="20px" >
                                <ul class="dropdown-menu">
                                  <li><a class="dropdown-item" href="{% url 'blog_app:editpost' i.id %}">Edit</a></li>
                                  <li><a class="dropdown-item" href="{% url 'blog_app:deletepost' i.id %}">Delete</a></li>
                                </ul>
                              </div>
                            {% endif %}
                        <li><p style="font-size:medium; font-family:Helvetica">{{i.description}}</p></li>
                        {% if i.image %}
                        <li><img src="{{ i.image.url }}" alt="" width="75%"></li>
                        {% endif %}
                        <li><p style="color: rgb(100, 100, 100); font-size:smaller;">{{i.date}}</p>
                            
                        </li>
                    </ul>
                </div>
                <br>
            </div>
          
            <hr><hr>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
<br><br>
<center><b><h4 style="font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">NO POSTS</h4></b></center>
{% endif %}
{% endblock %}